title: Yu-Ting Hsiung
languageCode: zh-TW
defaultContentLanguage: zh-tw
hasCJKLanguage: true # 字數統計計入中文
theme: PaperMod
paginate: 10
params:
  env: production
  homeInfoParams:
    Title: Biography
    Content: Yu-Ting Hsiung is a full-stack developer at Synology. Double major in Computer Science and Mathematics at National Taiwan University. Interested in web development and data analysis. Used to be a teaching assistant for the courses "Data Structure and Algorithms", "Algorithm Design and Analysis" in NTU CSIE, and "Calculus" in NTU Math. Open to coffee chat.
  # ShowShareButtons: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowFullTextinRSS: true
  ShowWordCount: true
  ShowPostNavLinks: true
  defaultTheme: dark
  comments: true
  editPost:
    URL: "https://github.com/bearomorphism/bearomorphism-hugo/edit/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
  socialIcons:
    - name: github
      url: "https://github.com/bearomorphism"
    - name: linkedin
      url: "https://www.linkedin.com/in/%E8%82%B2%E9%9C%86-%E7%86%8A-4622171b4/"
    - name: facebook
      url: "https://www.facebook.com/yu.ting.hsiung.bearomorphism/"
    - name: instagram
      url: "https://www.instagram.com/bearomorphism/"
    - name: strava
      url: "https://www.strava.com/athletes/33243038"
    - name: cv
      url: "https://drive.google.com/file/d/1qeMsSqrg8v4ka4Y4vy4CpF0oeV4aJxay/view"
    - name: email
      url: "mailto:bear890707@gmail.com"
disqusShortname: yu-ting-hsiung
outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 15
    - identifier: blog
      name: Blog
      url: /posts/blog/
      weight: 17
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: CV
      name: CV
      url: 'https://drive.google.com/file/d/1qeMsSqrg8v4ka4Y4vy4CpF0oeV4aJxay/view'
      weight: 40
    - identifier: random-notes
      name: Notes
      url: /posts/notes/
      weight: 70
    - identifier: log
      name: Log
      url: /posts/log/
      weight: 80
