title: Yu-Ting Hsiung
baseurl: /
languageCode: en-us
theme: PaperMod
paginate: 5
params:
  env: production
  homeInfoParams:
    Title: 嗨，你今天過得好嗎？
    Content: 要看比較有知識點的東西可以看看[這裡](/posts/blog)，或者點一些底下的 icon
  # ShowShareButtons: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowFullTextinRSS: true
  defaultTheme: dark
  comments: true
  socialIcons:
    - name: github
      url: "https://github.com/bearomorphism"
    - name: linkedin
      url: "https://www.linkedin.com/in/%E8%82%B2%E9%9C%86-%E7%86%8A-4622171b4/"
    - name: facebook
      url: "https://www.facebook.com/yu.ting.hsiung.bearomorphism/"
    - name: instagram
      url: "https://www.instagram.com/bearomorphism/"
    - name: strava
      url: "https://www.strava.com/athletes/33243038"
    - name: cv
      url: "https://drive.google.com/file/d/1qeMsSqrg8v4ka4Y4vy4CpF0oeV4aJxay/view"
    - name: email
      url: "mailto:bear890707@gmail.com"
disqusShortname: yu-ting-hsiung
outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 15
    - identifier: blog
      name: Blog
      url: /posts/blog/
      weight: 17
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: CV
      name: CV
      url: 'https://drive.google.com/file/d/1qeMsSqrg8v4ka4Y4vy4CpF0oeV4aJxay/view'
      weight: 40
    - identifier: random-notes
      name: Notes
      url: /posts/notes/
      weight: 70
